[package]
name = "surrealdb_c"
version = "0.1.0"
edition = "2021"
authors = ["Tobie Morgan Hitchcock <tobie@surrealdb.com>"]
description = "WebAssembly driver for SurrealDB"
repository = "https://github.com/surrealdb/surrealdb.wasm"
license = "Apache License 2.0"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
surrealdb = { git = "https://github.com/surrealdb/surrealdb.git", tag = "v2.0.0-beta.1", features = [
    "kv-surrealkv",
    "kv-mem",
    "http",
] }
surrealdb-core = { git = "https://github.com/surrealdb/surrealdb.git", tag = "v2.0.0-beta.1", features = [
    "http",
] }
tokio = { version = "1.39.3", features = ["full"] }
uuid = "1.9.1"
futures = "0.3.30"
libc = "0.2.158"
chrono = "0.4.38"
async-channel = "2.3.1"
ciborium = "0.2.2"

[build-dependencies]
cbindgen = "0.27.0"
