[config]
skip_core_tasks = true
reduce_output = true

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.build-release]
command = "cargo"
args = ["build", "--release"]

[tasks.test]
dependencies = ["build"]
script = [
    "cargo test",
    "test/test.exe",
]

[tasks.test-scratch]
dependencies = ["build"]
script = [
    "cargo test",
    "test/test_scratch.exe",
]

[tasks.test-doc]
dependencies = ["build"]
script = [
    "cargo test",
    "test/doc.exe",
]
