[config]
skip_core_tasks = true
reduce_output = true

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.build-release]
command = "cargo"
args = ["build", "--release"]

[tasks.test]
dependencies = ["build"]
script = [
    "cc -L./target/debug -lsurrealdb_c -lpthread -otest/a.out test/test.c",
    "test/a.out",
]

[tasks.test-doc]
dependencies = ["build"]
script = [
    "cc -L./target/debug -lsurrealdb_c -lpthread -otest/doc.out test/doc.c",
    "test/doc.out",
]
